In [1]:
import pandas as pd 
df = pd.read_excel("/Users/kri/Downloads/ngo_raw_excel file.xlsx")
print(df.shape)
df.head(10)

(9155, 30)

,ncode,org_name,region,international,regional,national,local,address,last_line_of_address,country_of_activity,...,population,public_admin,statistics,sustainable_development,peace_and_development_in_africa,conflict_resolution_in_africa,nepad,page,page_item,complete
0,1,"""Fondation - Afrique développement internation...",Africa,True,False,False,False,Rue de l'OCAM prolongée Kotokoukondji BP 61528...,Togo,Belgium | Congo | Côte D'Ivoire | Benin | Came...,...,True,True,True,True,True,True,True,1,1,True
1,2,1GOAL: Global Campaign for Education,Africa,True,False,False,False,"26 Baker Street, Rosebank, Johannesburg, 2132 ...",South Africa,unable to find country of activity field,...,False,False,False,False,False,False,False,1,2,True
2,3,A3 Foundation nig,Africa,True,False,False,False,"No.45 Ajose Adeogun street utako ,Jabi Distric...",Nigeria,United States of America | Ghana | Nigeria,...,False,False,False,True,True,False,True,1,3,True
3,4,AATASSIMO,Africa,True,False,False,False,"37,rue de Cologne le Belvédère 1002 Tunis ZAP ...",Tunisia,Djibouti | Belgium | Senegal | Algeria | Togo ...,...,True,False,False,True,True,True,True,1,4,True
4,5,Abantu for Development (People for Development),Africa,True,False,False,False,P.O. Box K.D.4 ZAP Kanda-Accra Ghana,Ghana,unable to find country of activity field,...,False,False,False,False,False,False,False,1,5,True
5,6,Ability Focus,Africa,True,False,False,False,"Plot 1503 Ubiaja Crescent, Garki 2, Abuja ZAP ...",Nigeria,Nigeria,...,False,True,True,True,True,True,True,1,6,True
6,7,Academie Diplomatique Africaine,Africa,True,False,False,False,Complexe Sicap-Point E Bat. B - 3e Et. 12500 -...,Senegal,unable to find country of activity field,...,False,False,False,True,False,False,False,1,7,True
7,8,Academy for Future Science,Africa,True,False,False,False,"2 Victoria StreetSandringham, Johannesburg 219...",South Africa,Brazil | Bolivia (Plurinational State of) | So...,...,False,True,False,True,False,False,False,1,8,True
8,9,Accidentés du Monde,Africa,True,False,False,False,11 BP 2117 Abidjan 11 Côte D'Ivoire,Côte D'Ivoire,unable to find country of activity field,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,9,True
9,10,ACTION CONTRE LA PAUVRETE POUR LE DEVELOPPEMEN...,Africa,True,False,False,False,VILLAGE DE BIMON ROUTE DE MBAÏKI OMBELLA MPOKO...,Central African Republic,Central African Republic,...,True,True,True,True,False,False,False,1,10,True

In [4]:
df.isnull().sum().sort_values(ascending=False)

area_of_expertise_note             8048
nepad                              1107
conflict_resolution_in_africa      1107
peace_and_development_in_africa    1107
sustainable_development            1107
statistics                         1107
public_admin                       1107
population                         1107
gender_issues_and_adv_of_women     1107
financing_for_development          1107
economic_social                    1107
affiliation_with_ngo_networks        74
ncode                                 0
page_item                             0
page                                  0
main_objective                        0
org_name                              0
language                              0
millenium_development_goals           0
un_consultative_year                  0
establishment_year                    0
country_of_activity                   0
last_line_of_address                  0
address                               0
local                                 0
national                              0
regional                              0
international                         0
region                                0
complete                              0
dtype: int64

In [6]:
## duplicates and missing values 

df = df.drop_duplicates()


df['statistics'] = df['statistics'].fillna("False")
df['population'] = df['population'].fillna("False")
df['public_admin'] = df['public_admin'].fillna("False")
df['area_of_expertise_note'] = df['area_of_expertise_note'].fillna("")
df['region'] = df['region'].fillna("Unknown")
theme_cols = [
    "nepad",
    "conflict_resolution_in_africa",
    "peace_and_development_in_africa",
    "sustainable_development",
    "statistics",
    "public_admin",
    "population",
    "gender_issues_and_adv_of_women",
    "financing_for_development",
    "economic_social"
]

df[theme_cols] = df[theme_cols].fillna(0)
df['affiliation_with_ngo_networks'] = df['affiliation_with_ngo_networks'].fillna("Unknown")

df.isnull().sum().sort_values(ascending=False)

ncode                              0
org_name                           0
page_item                          0
page                               0
nepad                              0
conflict_resolution_in_africa      0
peace_and_development_in_africa    0
sustainable_development            0
statistics                         0
public_admin                       0
population                         0
gender_issues_and_adv_of_women     0
financing_for_development          0
economic_social                    0
area_of_expertise_note             0
main_objective                     0
language                           0
millenium_development_goals        0
affiliation_with_ngo_networks      0
un_consultative_year               0
establishment_year                 0
country_of_activity                0
last_line_of_address               0
address                            0
local                              0
national                           0
regional                           0
international                      0
region                             0
complete                           0
dtype: int64

In [9]:
## better features 
df["ngo_profile"] = (
    df["main_objective"] + " " +
    df["area_of_expertise_note"] + " " +
    df["region"]
)
df['establishment_year'] = pd.to_numeric(df['establishment_year'], errors='coerce')
df = df[df['establishment_year'] > 1900]
df["ngo_profile"] = df["ngo_profile"].str.lower()
import os

os.makedirs("dataset", exist_ok=True)
df.to_csv("dataset/ngo_clean.csv", index=False)
df.head(10)

,ncode,org_name,region,international,regional,national,local,address,last_line_of_address,country_of_activity,...,public_admin,statistics,sustainable_development,peace_and_development_in_africa,conflict_resolution_in_africa,nepad,page,page_item,complete,ngo_profile
0,1,"""Fondation - Afrique développement internation...",Africa,True,False,False,False,Rue de l'OCAM prolongée Kotokoukondji BP 61528...,Togo,Belgium | Congo | Côte D'Ivoire | Benin | Came...,...,True,True,True,True,True,True,1,1,True,special event / application for consultative s...
2,3,A3 Foundation nig,Africa,True,False,False,False,"No.45 Ajose Adeogun street utako ,Jabi Distric...",Nigeria,United States of America | Ghana | Nigeria,...,False,False,True,True,False,True,1,3,True,nepad/office of the special adviser on africa ...
3,4,AATASSIMO,Africa,True,False,False,False,"37,rue de Cologne le Belvédère 1002 Tunis ZAP ...",Tunisia,Djibouti | Belgium | Senegal | Algeria | Togo ...,...,False,False,True,True,True,True,1,4,True,special event / application for consultative s...
5,6,Ability Focus,Africa,True,False,False,False,"Plot 1503 Ubiaja Crescent, Garki 2, Abuja ZAP ...",Nigeria,Nigeria,...,True,True,True,True,True,True,1,6,True,special event / application for consultative s...
6,7,Academie Diplomatique Africaine,Africa,True,False,False,False,Complexe Sicap-Point E Bat. B - 3e Et. 12500 -...,Senegal,unable to find country of activity field,...,False,False,True,False,False,False,1,7,True,special event / application for consultative s...
7,8,Academy for Future Science,Africa,True,False,False,False,"2 Victoria StreetSandringham, Johannesburg 219...",South Africa,Brazil | Bolivia (Plurinational State of) | So...,...,True,False,True,False,False,False,1,8,True,sustainable development africa
9,10,ACTION CONTRE LA PAUVRETE POUR LE DEVELOPPEMEN...,Africa,True,False,False,False,VILLAGE DE BIMON ROUTE DE MBAÏKI OMBELLA MPOKO...,Central African Republic,Central African Republic,...,True,True,True,False,False,False,1,10,True,sustainable development africa
10,11,Action de Jeunes Congolais pour l'Épanouisseme...,Africa,True,False,False,False,"120, Av tshela, C/Kinshasa Democratic Republic...",Democratic Republic of the Congo,Democratic Republic of the Congo,...,False,False,False,False,False,False,1,11,True,special event / application for consultative s...
11,12,Action Health Incorporated,Africa,True,False,False,False,"17 Lawal Street, off Oweh StreetJibowu, Yaba, ...",Nigeria,unable to find country of activity field,...,False,False,False,False,False,False,1,12,True,advancement of women africa
12,13,Action pour la promotion du développement,Africa,True,False,False,False,"32, Avenue Sembé, Arrondissement II OUESSO Dép...",Congo,Belgium | Romania | Jamaica | Panama | Ukraine...,...,True,True,True,True,True,True,1,13,True,special event / application for consultative s...

In [23]:


import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

df = pd.read_csv("dataset/ngo_clean.csv")

df["main_text"] = (
    (df["main_objective"].fillna('') + " ") * 3 +
    (df["area_of_expertise_note"].fillna('') + " ") * 2
).str.lower()

df["region_text"] = df["region"].fillna('').str.lower()

vectorizer_main = TfidfVectorizer(stop_words='english', max_df=0.8, min_df=3)
vectorizer_region = TfidfVectorizer()

tfidf_main = vectorizer_main.fit_transform(df["main_text"])
tfidf_region = vectorizer_region.fit_transform(df["region_text"])

def recommend_ngos(query, region_query, top_n=5):
    query_main = vectorizer_main.transform([query])
    query_region = vectorizer_region.transform([region_query.lower()])
    
    sim_main = cosine_similarity(query_main, tfidf_main).flatten()
    sim_region = cosine_similarity(query_region, tfidf_region).flatten()
    
    df_temp = df.copy()
    df_temp["main_score"] = sim_main
    df_temp["region_score"] = sim_region
    
    df_temp = df_temp[df_temp["region_score"] == 1.0]
    
    df_temp["final_score"] = df_temp["main_score"]
    
    if len(df_temp) < top_n:
        df_temp = df.copy()
        df_temp["final_score"] = sim_main
    
    df_temp = df_temp.sort_values(by="final_score", ascending=False)
    
    return df_temp.head(top_n)[[
        "org_name",
        "region",
        "country_of_activity",
        "final_score"
    ]]


recommend_ngos("women empowerment governance", "Africa")

,org_name,region,country_of_activity,final_score
1450,Federation of Women Lawyers in Kenya,Africa,Kenya,0.707107
527,African Women's Development & Communication Ne...,Africa,Kenya,0.707107
2390,Women in Law and Development in Africa [Femmes...,Africa,Togo,0.707107
540,Alliance for Arab Women,Africa,Egypt,0.707107
544,Amanitare Sexual Rights Network,Africa,South Africa | Zambia | Uganda | Zimbabwe | Mo...,0.707107

In [24]:
def build_query(volunteer):
    skills_text = " ".join(volunteer["skills"]) * 2
    interest_text = volunteer["interest"] * 3
    location_text = volunteer["location"]
    
    query = f"{skills_text} {interest_text} {location_text}"
    return query.lower()

def map_location_to_region(location):
    location = location.lower()
    
    if location in ["india", "china", "japan"]:
        return "asia"
    elif location in ["nigeria", "kenya", "ghana"]:
        return "africa"
    elif location in ["usa", "canada"]:
        return "north america"
    else:
        return "asia"

def match_volunteer(volunteer, top_n=5):
    query = build_query(volunteer)
    region = map_location_to_region(volunteer["location"])
    
    results = recommend_ngos(query, region, top_n)
    
    return results
volunteer = {
    "skills": ["teaching", "education"],
    "interest": "women empowerment",
    "location": "India"
}

match_volunteer(volunteer)

,org_name,region,country_of_activity,final_score
3622,Rural Women's Network Nepal,Asia,Nepal,0.707107
3314,ALNAHDA PHILANTHROPIC SOCIETY for WOMEN,Asia,Saudi Arabia,0.707107
3729,Women Empowerment and Human Resource Developme...,Asia,India,0.707107
3733,Women's Empowerment Group,Asia,Pakistan,0.707107
3737,Women's Welfare Centre,Asia,India,0.707107